### ISSUE TITLE
Feature request: tbl_svysummary %>% add_difference(test = XYZ)

### ISSUE THREAD

**Issue by LuiNov** [ddsjoberg/gtsummary#1119]
Hello, 

first of all I was surprised (+ happy) to see the function %>% add_difference work for survey summary objects!!! But if I'm right it only allows differences for continuous variables (?). 

It would be great to have an option to add the differences in proportions. I'm not sure if there are weighted tests available but if not just a group 1 % - group 2 % = Diff output would be great (without test then).

If there are already options to do that please correct me. Here's the code that works:

```
library(pacman)
p_load(smd, gtsummary)

gtsummary::trial %>% 
mutate(weight_num  = case_when(trt == "Drug A" ~ 98/200, 
trt == "Drug B" ~ 102/200) ) %>% rowid_to_column() %>% 
as_survey_design(ids = rowid, weights = weight_num) %>% 
tbl_svysummary(., by  = "trt", include = c("age", "stage")  ) %>% 
add_difference(test = list(all_continuous() ~"smd"), include = all_continuous())
```

Here what doesn't work: 
```
gtsummary::trial %>% 
  mutate(weight_num  = case_when(trt == "Drug A" ~ 98/200, 
                                 trt == "Drug B" ~ 102/200) ) %>% rowid_to_column() %>% 
  as_survey_design(ids = rowid, weights = weight_num) %>% 
  tbl_svysummary(., by  = "trt", include = c("age", "stage")  ) %>% 
    add_difference()

Fehler: Problem with `mutate()` column `test`.
ℹ `test = map2(...)`.
x There is no default test for variable 'age'. Please specify method in `test=` or
exclude it with `include = -c(age)`
Backtrace:
  1. `%>%`(...)
 14. base::.handleSimpleError(...)
 15. dplyr:::h(simpleError(msg, call))
```

I also can't add tests like "paired.wilcox.test" or "prop.test". So "smd" is the only test available?
The code below runs but only gives the Diff for age. And it throws up a ton of numbers on the console...I think he doesn't like to do that :-( 

```
 .... %>% 
    add_difference(test = list(all_continuous() ~"smd", all_categorical()~ "prop.test") , include = c("age", "stage")  )

There was an error in 'add_p()/add_difference()' for variable 'stage', p-value omitted:
Error in (function (x, n, p = NULL, alternative = c("two.sided", "less", : unbenutzte Argumente (data = list(list(1:200), list(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)), FALSE, c(2.04081632653061, 1.96078431372549, 2.04081632653061, 2.04081632653061, 2.04081632653061, 1.96078431372549, 2.04081632653061, 2.04081632653061, 2.04081632653061, 1.96078431372549, 1.96078431372549, 1.96078431372549, 1.96078431372549, 1.96078431372549, 1.96078431372549, 1.96078431372549, 2.04081632653061, 1.96078431372549, 2.04081632653061, 2.04081632653061, 
......

632653061, 2.04081632653061, 1.96078431372549, 2.04081632653061, 1.96078431372549, 2.04081632653061, 2.04081632653061, 2.04081632653061, 2.04081632653061)), "Called via srvyr", list(1:200, c("Drug A", "Drug B", "Drug A", "Drug A", "Drug A", "Drug B", "Drug A", "Drug A", "Drug A", "Drug B", "Drug B", "Drug B", "Drug B", "Drug B", "Drug B", "Drug B", "Drug A", "Drug B", 
"Drug A", "Drug A", "Drug A", "Drug A", "Drug A", "Drug A", "Drug B", "Drug B", "Drug
```

Thanks, 
Luise

**Comment by ddsjoberg** [comment]
Hallo @LuiNov ! Danke sehr for the post!

The "smd" method works for all categorical, continuous, and dichotomous variables. Since there is no default method assigned for svy methods, it returned an error. svy methods are the only versions that don't have default methods, and seeing this in action, I see that the throwing an error may not be the best messaging. Probably be best to just omit those variables from the calculations instead of throwing that error...... 🤔 🤔 

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.5.1.9000'

tbl <-
  survey::svydesign(ids = ~1, data = trial, weights = ~1) %>%
  tbl_svysummary(by = trt, missing = "no", include = c(response, age, grade)) 

# standardize mean differences for all variables
tbl %>%
  add_difference(test = everything() ~ "smd") %>%
  bold_labels() %>%
  as_kable() # convert to kable for github
```

| **Characteristic** | **Drug A**, N = 98 | **Drug B**, N = 102 | **Difference** | **95% CI**  |
|:-------------------|:------------------:|:-------------------:|:--------------:|:-----------:|
| **Tumor Response** |      28 (29%)      |      33 (34%)       |     -0.09      | -0.37, 0.19 |
| **Age**            |    46 (37, 58)     |     48 (38, 56)     |     -0.03      | -0.32, 0.25 |
| **Grade**          |                    |                     |      0.07      | -0.20, 0.35 |
| I                  |      35 (36%)      |      33 (32%)       |                |             |
| II                 |      32 (33%)      |      36 (35%)       |                |             |
| III                |      31 (32%)      |      33 (32%)       |                |             |

I am also going to add a method for least-square means (or margin means) for svy designs.
``` r
# marginal means for age and response (doesn't work categorical data)
tbl %>%
  add_difference(test = c(age, response) ~ "emmeans", include = -grade) %>%
  bold_labels() %>%
  as_kable() # convert to kable for github
```

| **Characteristic** | **Drug A**, N = 98 | **Drug B**, N = 102 | **Difference** | **95% CI** | **p-value** |
|:-------------------|:------------------:|:-------------------:|:--------------:|:----------:|:-----------:|
| **Tumor Response** |      28 (29%)      |      33 (34%)       |     -4.2%      | -17%, 8.9% |     0.5     |
| **Age**            |    46 (37, 58)     |     48 (38, 56)     |     -0.44      | -4.6, 3.7  |     0.8     |
| **Grade**          |                    |                     |                |            |             |
| I                  |      35 (36%)      |      33 (32%)       |                |            |             |
| II                 |      32 (33%)      |      36 (35%)       |                |            |             |
| III                |      31 (32%)      |      33 (32%)       |                |            |             |

<sup>Created on 2022-01-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
