### ISSUE TITLE
Bug Report: translate “to” in date range

### ISSUE THREAD

**Issue by msberends** [ddsjoberg/gtsummary#1303]
As discussed in #1302, the word “to”, used in date ranges, is not translated to foreign languages.

**Comment by ddsjoberg** [comment]
Hello @msberends ! Thanks for letting me know about this. 

I went to go implement the translation in this case, and ran into an issue: the default data statistic is `"{min} to {max}"`. Since the work "to" is in a string that already relies on curly brackets to identify the summary functions.

Unfortunately, the user will need to change the static themselves:

```r
tbl_summary(
  statistic = list(date_varname = "{min} tot {max}"
}
```

My Dutch colleague will finish reviewing the other translations this week FYI
