### ISSUE TITLE
tbl_summary() displays excessive number of decimals for SDs of dates

### ISSUE THREAD

**Issue by huftis** [ddsjoberg/gtsummary#1339]
When showing the standard deviation of dates, `tbl_summary()` displays an excessive number of decimals. Reprex:

```r
library(gtsummary)
d = data.frame(
  date = as.Date(c("1956-01-01", "2022-09-14")),
  year = c(1956, 2022)
)
tbl_summary(d,
  type = everything() ~ "continuous", # Needed for year, not date
  statistic = all_continuous() ~ "{mean} ({sd})",
)
```

Output:

![image](https://user-images.githubusercontent.com/100251/190144797-5555d4f4-781d-43c0-a6f6-cc1ee7359384.png)

The number shown is the standard deviation measured in *days*. (17227/365 ≈ 47, which is the SD for the corresponding `year` variable.)

Expected output:
Showing the SD with a unit would be nice, e.g.:

17,227 days
or
47.2 years   [using 365.2524 days/year]

**Comment by ddsjoberg** [comment]
dates are different for many reasons. you can change the formatting of the summary statistics using the `digits=` argument.

**Comment by huftis** [comment]
> dates are different for many reasons. you can change the formatting of the summary statistics using the `digits=` argument.

Sure, but it would be nice with some reasonable *default* formatting. Having microsecond precision for a unit measured in *days* does seem excessive. Also note that if we simple drop the class, the precision is much more sensible (0 decimals):

```r
library(gtsummary)
d = data.frame(date = as.Date(c("1956-01-01", "2022-09-14")))
d$days = unclass(d$date)
tbl_summary(d,
  type = everything() ~ "continuous", # Needed for year, not date
  statistic = all_continuous() ~ "{mean} ({sd})",
)
```

![image](https://user-images.githubusercontent.com/100251/190233344-da6955f8-c6c5-4640-9de3-bd349e757ff9.png)

So even treating it as an ordinary number when calculating the SD would be a big improvement.

**Comment by ddsjoberg** [comment]
I agree with you that the precision is excessive. The point I am trying to make is that the handling of dates is different from every other data type. Most users are reporting min/max/median/Q1/Q3....statistics that could be actual dates, rather than the mean or SD. While the SD of a vector of dates is something R _can_ compute, it's not often computed and it's interpretation is strange for anyone not familiar with the way dates are stored in R. If you're interested in reporting days since 1970, for example,  then I would convert your dates to numbers before passing to tbl_summary(). that will bypass all the special handling that dates get (and that you dont prefer).

**Comment by huftis** [comment]
Fair point. In practice, I would seldom report a standard deviation for a date variable. I was just surprised when doing so resulted in a ten-decimal number. 😃
