### ISSUE TITLE
Feature request: Pass `tidy_plus_plus()` args via `tbl_uvregression()`

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#1396]
Related to #1383

cc @larmarange @yuryzablotski

**Comment by ddsjoberg** [comment]
Add an example to the gallery as well

**Comment by kwakuduahc1** [comment]
There appears to be an issue with `tidy_plus_plus` which affects the `tbl_regression` function.

```
carData::Arrests |>
                 rstanarm::stan_glm(formula = released ~ colour + year + age, family = binomial(), chains = 1, iter = 100) |>
                 gtsummary::tbl_regression(
                   exponentiate = T)
```

The exponent of a negative number will always produce a positive number but the `tidy_plus_plus` function does not:

![image](https://user-images.githubusercontent.com/11381582/207302599-4d2363ce-0f87-41c7-814a-dd0978195df8.png)

However, if you change the `tidy_fun` parameter to use the tidy_parameters, things work as expected. I know this is not an issue with tbl_summary because I used the `tidy_plus_plus` function independently and it resulted in the same error.

```
carData::Arrests |>
                  rstanarm::stan_glm(formula = released ~ colour + year + age, family = binomial(), chains = 1, iter = 100) |>
                  gtsummary::tbl_regression(
                    exponentiate = T,
                    tidy_fun = broom.helpers::tidy_parameters)
```
![image](https://user-images.githubusercontent.com/11381582/207303828-041ed89a-a6ae-4762-84e3-09beff324c9b.png)

*NB:* The number of iterations does not affect the output. I reduced it to make it run faster. Using `brm` function from the `brms` package results in the same error. I would be raising the issue with the respective owners but I think it must be considered in its use with `tbl` functions
