### ISSUE TITLE
Bug Report: style_pvalue() returns wrong values for p-values from the coin package

### ISSUE THREAD

**Issue by huftis** [ddsjoberg/gtsummary#1460]
For *p*-values based on tests from the coin package, `style_pvalue()` returns incorrect *p*-values. For example, a *p*-value of 0.07 is shown as `<0.001`. The *p*-values from the coin package are normal numeric values, just with the added `pvalue` class. Here is a simple reprex:

```r
library(coin)
library(gtsummary)
tab = as.table(matrix(c(2, 8, 50, 45), ncol = 2))
p = midpvalue(independence_test(tab, distribution = "exact"))

# The actual p-value is ~0.072
p
#> [1] 0.07228752
dput(p)
#> structure(0.0722875208363881, class = c("pvalue", "numeric"))
as.numeric(p)
#> [1] 0.07228752
format(p)
#> [1] "0.07228752"

# But style_pvalue() incorrectly shows it as a much lower value
style_pvalue(p)
#> [1] <0.001
```

Expected output: `"0.072"`

**Comment by ddsjoberg** [comment]
Thanks for the report. That is surely strange. As an interim solution, you can unclass the p-value before passing to `style_pvalue()`

``` r
library(coin)
#> Loading required package: survival
library(gtsummary)
tab = as.table(matrix(c(2, 8, 50, 45), ncol = 2))
p = midpvalue(independence_test(tab, distribution = "exact"))

# The actual p-value is ~0.072
p
#> [1] 0.07228752
dput(p)
#> structure(0.0722875208363881, class = c("pvalue", "numeric"))
as.numeric(p)
#> [1] 0.07228752
format(p)
#> [1] "0.07228752"

# But style_pvalue() incorrectly shows it as a much lower value
unclass(p) |> style_pvalue()
#> [1] "0.072"
style_pvalue(p)
#> [1] <0.001
```

<sup>Created on 2023-02-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
In the style function we retain the attributes of the original vector. This was primarily intended for attributes like named vectors or labels. The coin package adds a p-value/numeric class that is also retained. The p-values are accurately rounded/formatted with `style_pvalue()`, but the coin package's print method takes over when displaying the result and shows the character p-value as `<0.001` instead of it's true character value.

A fix would be to retain all attributes except the class.

``` r
library(coin)
#> Loading required package: survival
library(gtsummary)

tab <- as.table(matrix(c(2, 8, 50, 45), ncol = 2))
p <- midpvalue(independence_test(tab, distribution = "exact"))
p
#> [1] 0.07228752
style_pvalue(p)
#> [1] <0.001

# the print method in coin takes over and formats the string
a_string <- "034234"
class(a_string) <- c("pvalue", "numeric")
a_string
#> [1] <2.22044604925031e-16
```

<sup>Created on 2023-02-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
