### ISSUE TITLE
Bug Report: Can't change Overall discription

### ISSUE THREAD

**Issue by dax44** [ddsjoberg/gtsummary#1505]
Using `add_overall` I want to change "Overal" to  "Total".

---

The following code doesn't change the description :(

```r
iris |> 
tbl_summary(by = Species) |> 
add_overall(col_label = "Total:, N = {N}")
```

**Comment by ddsjoberg** [comment]
Thank you @dax44 for the post! This was a regression in the last release and has been fixed in the dev version. In the meantime you can use the `modify_header()` function to specify the header label.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.7.1'

iris |> 
  tbl_summary(by = Species) |> 
  add_overall() |> 
  modify_header(stat_0 = "**Total**, N = {N}") |> 
  as_kable() # convert to kable to display on github
```

| **Characteristic** | **Total**, N = 150 | **setosa**, N = 50 | **versicolor**, N = 50 | **virginica**, N = 50 |
|:-------------------|:------------------:|:------------------:|:----------------------:|:---------------------:|
| Sepal.Length       | 5.80 (5.10, 6.40)  | 5.00 (4.80, 5.20)  |   5.90 (5.60, 6.30)    |   6.50 (6.23, 6.90)   |
| Sepal.Width        | 3.00 (2.80, 3.30)  | 3.40 (3.20, 3.68)  |   2.80 (2.53, 3.00)    |   3.00 (2.80, 3.18)   |
| Petal.Length       | 4.35 (1.60, 5.10)  | 1.50 (1.40, 1.58)  |   4.35 (4.00, 4.60)    |   5.55 (5.10, 5.88)   |
| Petal.Width        | 1.30 (0.30, 1.80)  | 0.20 (0.20, 0.30)  |   1.30 (1.20, 1.50)    |   2.00 (1.80, 2.30)   |

<sup>Created on 2023-05-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
