### ISSUE TITLE
Bug Report: tbl_stack uses the header footnotes from the first table only

### ISSUE THREAD

**Issue by oliviercailloux** [ddsjoberg/gtsummary#1511]
Building several tbl_summary with add_p and then stacking them with tbl_stack results in a table where the header for the p-value column reports (as a footnote) only the tests used for the first table.

**Comment by ddsjoberg** [comment]
Hi @oliviercailloux , thanks for the post

The `tbl_stack()` function is general and works with any gtsummary table, which is why I can't simply intuit what every updated column header or footnote should be after stacking.

I tried to make this as clear as possible by printing a note that the headers from the first stacked table take precedent over all the others when there are differences.

Unfortunately, I don't think I can know what the text should read and leave it to the users to update as needed. You can update the footnotes with `modify_footnote()`.

**Comment by ddsjoberg** [comment]
When the headers are different youll see this note in the console when you create the table, "ℹ Column headers among stacked tables differ. Headers from the first table are used. Use `quiet = TRUE` to suppress this message." Footnotes are trickier to to work with unfortunately, so if the only difference is a footnote, the user will have needed to read the function's help file for the details.
