### ISSUE TITLE
Bug Report: error when using coxphf in tbl_uvregression

### ISSUE THREAD

**Issue by hichew22** [ddsjoberg/gtsummary#1559]
Hello,

I am trying to use Cox regression with the Firth-penalized likelihood within tbl_uvregression as follows:

```
tbl_uvregression <- trial %>%
  select(death,
         ttdeath,
         age) %>%
  tbl_uvregression(
    method = coxphf,
    y = Surv(ttdeath, death),
    exponentiate = TRUE,
    pvalue_fun = ~ style_pvalue(.x, digits = 2)
  ) %>%
  add_nevent() %>%
  bold_p() %>%
  bold_labels()
```
However, the following error occurs:
```
Error in `mutate()`:
ℹ In argument: `model = map(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `value[[3L]]()`:
! Error in cbind(obj$mm1, obj$timedata): number of rows of matrices must match (see arg 2)
Backtrace:
  1. ... %>% bold_labels()
 16. purrr::map(...)
 17. purrr:::map_("list", .x, .f, ..., .progress = .progress)
 21. gtsummary (local) .f(.x[[i]], ...)
 22. gtsummary:::safe_model_construction(.x, method, data, method.args)
 23. base::tryCatch(...)
 24. base (local) tryCatchList(expr, classes, parentenv, handlers)
 25. base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 26. value[[3L]](cond)
```

Is this because the coxphf package is not supported within tbl_uvregression or another bug?

Thank you!

**Comment by ddsjoberg** [comment]
Thanks for the report @hichew22 !

Here's a list of the supported models: https://www.danieldsjoberg.com/gtsummary/articles/tbl_regression.html#supported-models

This model type is not supported, but you can try to request support on the `broom.helpers` github page. Note that some models cannot be supported because they do not return the needed information to properly parse the model's information.
