### ISSUE TITLE
Feature request: Overall p-values when using strata in tbl_summary

### ISSUE THREAD

**Issue by JohnSodling** [ddsjoberg/gtsummary#1629]
Hello there!
Thanks for a great package! Helps alot with my research!

I have a proposal of an added function when using strata: I would like in a separate column to the right presenting p-values that are computed testing the overalls against eachother. Instead of just presenting p-values from within the strata.

Right now I'm constructing a completely separate table without strata and fuse them manually. 

Thanks alot!

```
# Simple example with (trial)

trial |> 
  select(age, grade, trt) |> 
  tbl_strata(
    strata = grade,
    .tbl_fun =
      ~ .x |> 
      tbl_summary(by = trt, missing = "no") |> 
      add_p() |> 
      add_overall(),
    .header = "**{strata}**, N = {n}"
  )

#Then adding the p-values from this example to the right:

trial |> 
  select(age, grade) |> 
      tbl_summary(by = grade, missing = "no") |> 
      add_p() |> 
      add_overall()
```

**Comment by ddsjoberg** [comment]
Dear @JohnSodling , Thanks for the post!

In this case, we have the `add_stat()` function to include additional column(s) with any statistics you like. That will be the best option for you.

Since `tbl_strata()` works with any gtsummary table (of which, there are many variants exported from this package and others), it would be tricky to provide contextually aware calculations after stratified tables are merged/stacked.

**Comment by JohnSodling** [comment]
Thanks for the fast response. Will look into the add_stat() further to implement it in my scripts.
Thanks!
