### ISSUE TITLE
More function with *add_n* and *add_overall*

### ISSUE THREAD

**Issue by DrDinhLuong** [ddsjoberg/gtsummary#1637]
Dear Developer

Thank you to develop nice package. 
In this section, Can you develop more felexible to caculate percent by *row*/*col* in *add_n* and *add_overal*.
because, some time we want to look including percent by *row* in *tbl_summary* and percent by *col* in0 *add_n* or *add_overal*.

Thank you so much

Luong

**Comment by ddsjoberg** [comment]
Dear @DrDinhLuong , Thanks for the post.

I think the best way to get at what you need is using `tbl_merge()` for add an overall column that is different from the primary table.

For `add_n()` with customized statistics, we have the `add_stat()` function for adding any statistics/results you'd like.

I prefer not to pack the primary functions with features, because it makes it easier to learn for new users.
