### ISSUE TITLE
Bug Report: Gtsummary generates inconsistent percentages that do not sum to 100

### ISSUE THREAD

**Issue by CharlyMarie** [ddsjoberg/gtsummary#1881]
Many bugs have been reported about gtsummary not generating percentages that sum to 100. It looks like the bug is still (very) present in version 2.0, which makes both tbl_summary() _and_ tbl_svysummary() untrustworthy.

Here is a reproducible example, taken from [a SO question](https://stackoverflow.com/questions/76827812/gtsummary-round-percentages-to-100). 

```r
library(dplyr)
library(gtsummary)
theme_gtsummary_compact()
set.seed(123)

numerical_var <- rnorm(200, mean = 50, sd = 10)
categories <- c("Category_A", "Category_B", "Category_C", "Category_D")
categorical_var1 <- sample(categories, 200, replace = TRUE)
categorical_var2 <- sample(categories, 200, replace = TRUE)
categorical_var3 <- sample(categories, 200, replace = TRUE)
weight_var <- runif(200, min = 0.003, max = 40)

# Create the data frame
df<- data.frame(
  num = numerical_var,
  cat1 = categorical_var1,
  cat2 = categorical_var2,
  cat3  = categorical_var3,
  wgt = weight_var
)

# Create design object 
svy_design <- survey::svydesign(
  ~1, 
  data = df, 
  weights = ~wgt
)

# Get frequencies
  # Normal
normal_design <- df %>%
  tbl_summary(
    by = cat1,
    statistic = all_categorical() ~ "{p}%"
  ) 

normal_design 

  # Survey
svy_table <- svy_design %>%
  tbl_svysummary(
    by = cat1,
    statistic = all_categorical() ~ "{p}%"
  ) 

svy_table
```

**In the table generated from tbl_summary()**
The sum of Column Category_C and the row cat2 adds up to 18 + 31 + 25 + 25 = 99
The sum of Column Category_C and the rows car3 adds up to 27 + 14 + 33 + 25 = 99

**In the table generated from tbl_svysummary()**
The sum of Column Category_A and the row cat2 adds up to 27 + 26 + 20 + 28 = 101

**Comment by larmarange** [comment]
If I may, this is not a bug. This is a classic but not trivial statistical issue due to rounding the result. When rounding numbers, using the usual rounding rules, the sum is not preserved.

Some have proposed rules to round numbers while preserving the sum (an example here: https://stackoverflow.com/a/40517571/7943547 or https://larmarange.github.io/JLutils/reference/round_preserve_sum.html ).

Right now, we cannot use directly a function like `round_preserve_sum()` in the digits argument of `tbl_summary()` as the number formatting is done cell per cell and not per column or row. Should it be an additional feature of `gtsummary`, it could be en open question for `gtsummary` team.

In all cases, the current behaviour is not a bug but the expected behaviours.

**Comment by ddsjoberg** [comment]
@CharlyMarie : if you've looked up the previous posts, then you must know this is not a bug. Rather, it's a (very) obvious consequence of rounding numbers. I've authored and co-authored ~300 papers in peer-reviewed journals, and no one has ever been confused by this (very) standard convention.

**Comment by CharlyMarie** [comment]
I looked at the previous posts and understood that the issue would be addressed in version 2. Hence my message to let you know that the behaviour was still present, but your answers clearly show my confusion.

Thanks as always for your replies :)

**Comment by ddsjoberg** [comment]
you can follow this issue, which when completed, will allow users to utilize functions like the one @larmarange suggested.
https://github.com/insightsengineering/cards/issues/285
