### ISSUE TITLE
Bug Report: new version of gtsummary struggles with hms types

### ISSUE THREAD

**Issue by malcolmbarrett** [ddsjoberg/gtsummary#1893]
gtsummary now struggles with hms objects

``` r
# remotes::install_github("LucyMcGowan/touringplans")
library(gtsummary)
```

``` r
# works with HMS as numbers, unrelated to gtsummary
touringplans::seven_dwarfs_train_2018 |>
  tbl_summary(by = park_extra_magic_morning, include = c(park_close))
```

``` r
library(hms)

# fails
touringplans::seven_dwarfs_train_2018 |>
  tbl_summary(by = park_extra_magic_morning, include = c(park_close))
#> Error in `dplyr::mutate()`:
#> ℹ In argument: `df_stats = list(...)`.
#> Caused by error in `dplyr::mutate()`:
#> ℹ In argument: `stat = map(...)`.
#> Caused by error:
#> ! Failed to evaluate glue component {n}
#> Caused by error:
#> ! object 'n' not found
```

``` r
# works
touringplans::seven_dwarfs_train_2018 |>
  dplyr::mutate(park_close = as.character(park_close)) |>
  tbl_summary(by = park_extra_magic_morning, include = c(park_close))
```

<sup>Created on 2024-08-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
Thank you so much for the report @malcolmbarrett ! Much appreciated!

This should be fixed in PR #1895. Can you take a look before I merge?

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '2.0.0.9003'
library(hms)

touringplans::seven_dwarfs_train_2018 |>
  tbl_summary(by = park_extra_magic_morning, include = c(park_close)) |> 
  as_kable()
```

| **Characteristic** | **0** N = 4,628 | **1** N = 994 |
|:-------------------|:---------------:|:-------------:|
| park_close         |                 |               |
| 16:30:00           |    8 (0.2%)     |    0 (0%)     |
| 18:00:00           |    645 (14%)    |   307 (31%)   |
| 20:00:00           |   238 (5.1%)    |   27 (2.7%)   |
| 21:00:00           |   387 (8.4%)    |    0 (0%)     |
| 22:00:00           |   1,375 (30%)   |   161 (16%)   |
| 23:00:00           |   1,272 (27%)   |   182 (18%)   |
| 24:00:00           |    688 (15%)    |   298 (30%)   |
| 25:00:00           |    15 (0.3%)    |   19 (1.9%)   |

<sup>Created on 2024-08-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

FYI, I am submitted a patch release as soon as CRAN re-opens from summer holiday.

**Comment by malcolmbarrett** [comment]
Works for me!

**Comment by ddsjoberg** [comment]
Thanks again @malcolmbarrett !
