### ISSUE TITLE
Bug Report: p value for add_p.tbl_survfit

### ISSUE THREAD

**Issue by kzkzmr** [ddsjoberg/gtsummary#1921]
Thanks for the great R package! It has helped me a lot.
The add_p.tbl_survfit function returns an incorrect p-value when applying a “survfit” function in a “for” structure.

library(tidyverse)
library(survival)
library(gtsummary)

# data generation
n <- 100
set.seed(12345)
x1 <- rbinom(n, 1, 0.5)
x2 <- rbinom(n, 1, 0.5)
et <- rexp(n) * exp(0.5 * x1) # effective only for "x1"
ec <- rexp(n) * 2
event <- 1 * (et < ec)
time <- et
time[event == 0] <- ec[event == 0]

dat <- data.frame(time, event, x1, x2)

# apply survfit function 
covv <- c("x1", "x2")
svf <- list()

for (i in 1:2){
  svf[[i]] <- survfit(formula(paste("Surv(time, event) ~", covv[i])), 
                              data = dat)
}

# Both p values are calculated for "x2"
svf %>% tbl_survfit(times = 1) %>%
  add_p(pvalue_fun = function(x) style_pvalue(x, digits = 3) )

# Calculate p values
a1 <- survdiff(Surv(time, event) ~ x1, data = dat)
a2 <- survdiff(Surv(time, event) ~ x2, data = dat)
round(a1$pvalue, 3) #p value for x1
round(a2$pvalue, 3) #p value for x2

**Comment by ddsjoberg** [comment]
Dear @kzkzmr , 

The reason the p-value is for the x2 result for both models is due to the fact that the formula in the survfit call is equal to the x2 model for both models. I've illustrated the issue with the way you've constructed the model, and two solutions. Hope that helps.



``` r
library(gtsummary)
library(survival)

set.seed(12345)

n <- 100; x1 <- rbinom(n, 1, 0.5); x2 <- rbinom(n, 1, 0.5)
et <- rexp(n) * exp(0.5 * x1); ec <- rexp(n) * 2; event <- 1 * (et < ec)
time <- et; time[event == 0] <- ec[event == 0]
dat <- data.frame(time, event, x1, x2)
covv <- c("x1", "x2")
svf <- list()

# the call does not reflect the true formula
for (i in 1:2){
  svf[[i]] <- survfit(formula(paste("Surv(time, event) ~", covv[i])), data = dat)
}
lapply(svf, \(x) x$call)
#> [[1]]
#> survfit(formula = formula(paste("Surv(time, event) ~", covv[i])), 
#>     data = dat)
#> 
#> [[2]]
#> survfit(formula = formula(paste("Surv(time, event) ~", covv[i])), 
#>     data = dat)

# inject the values into the table for the correct calculation
svf <- list()
for (i in 1:2){
  svf[[i]] <- rlang::inject(survfit(!!formula(paste("Surv(time, event) ~", covv[i])), data = dat))
}

tbl_survfit(svf, times = 1) |> 
  add_p() |> 
  as_kable() 
```

| **Characteristic** |   **Time 1**   | **p-value** |
|:-------------------|:--------------:|:-----------:|
| x1                 |                |    0.14     |
| 0                  | 35% (22%, 54%) |             |
| 1                  | 51% (37%, 70%) |             |
| x2                 |                |     0.8     |
| 0                  | 47% (32%, 69%) |             |
| 1                  | 41% (29%, 59%) |             |

``` r
  

# perhaps an easier way is to use the data frame method for `tbl_survfit.data.frame()`
dat |> 
  tbl_survfit(
    y = "Surv(time, event)",
    include = c("x1", "x2"),
    times = 1
  ) |> 
  add_p() |> 
  as_kable()
```

| **Characteristic** |   **Time 1**   | **p-value** |
|:-------------------|:--------------:|:-----------:|
| x1                 |                |    0.14     |
| 0                  | 35% (22%, 54%) |             |
| 1                  | 51% (37%, 70%) |             |
| x2                 |                |     0.8     |
| 0                  | 47% (32%, 69%) |             |
| 1                  | 41% (29%, 59%) |             |

<sup>Created on 2024-08-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by kzkzmr** [comment]
Dear @ddsjoberg,

Thank you very much for your help! 

Best,
Kazushi Maruo
