### ISSUE TITLE
Bug Report: Integer variables are interpreted as categorical variable

### ISSUE THREAD

**Issue by abduazizR** [ddsjoberg/gtsummary#2055]
I am trying to summarize the variable `gear` here as continuous. However, it's not allowing me to do so. Is this a bug or there's something wrong I am doing.

``` r
# this works but interpret the variable as categorical
library(gtsummary)
library(tidyverse)
mtcars  |> tibble()  |> tbl_summary(include = gear)
```

``` r
library(gtsummary)
library(tidyverse)
mtcars  |> tibble()  |> tbl_summary(statistic = list(cyl ~ "{median}"))
#> Error in `tbl_summary()`:
#> ! Statistic "median" is not available for variable "cyl".
#> ℹ Select among "n", "N", "p", "N_obs", "N_miss", "N_nonmiss", "p_miss", and
#>   "p_nonmiss".
```

<sup>Created on 2024-11-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by ddsjoberg** [comment]
@abduazizR : Please review the help file for `tbl_summary()`, specifically the section about types. I think that will address your question. https://www.danieldsjoberg.com/gtsummary/reference/tbl_summary.html#type-and-value-arguments

A note for future reports: we truly appreciate bug reports and keep them coming. It is often, however, best to start with a stackoverflow post asking a question on how to use the package. There are many users of the package on stackoverflow who can answer questions about the package, instead of requiring the maintainers of the package to respond to questions. Thanks for the post, and please re-open if you think you've found a bug.

**Comment by abduazizR** [comment]
My apologies.  Thank you so much

**Comment by ddsjoberg** [comment]
No problem, and thanks again for the post!
