### ISSUE TITLE
Anything Else?

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#208]
Hey Team @karissawhiting @zabore  @margarethannum !

I am going to submit gtsummary to rOpenSci and then to CRAN.  Are there any changes we should make before submitting?

Here are a couple of things that have been on my mind?
1. In `tbl_summary()` there is a `group =` argument.  Then in `add_p()` the `group = ` argument defaults to what was supplied in `tbl_summary()`.  `group = ` means nothing in context of `tbl_summary()`.  Should that argument be named something else, perhaps `no_print = `?  

1. Our package no longer depends {gt}, should we change the name? Perhaps something shorter?  Or if we just wait for gt to mature further, the outputs for all types (including MS Word) will look great.
    - `sumtbl` -  Stands for summary table, and I imagine we say "sum - T- B - L".  All the tables are referred to as summary tables throughout the documentation.
    - `tbl` - so short, but not descriptive
    - also, no change, so easy

Is there anything else you're not a fan of, or have thought of better names for?

**Comment by zabore** [comment]
Good point about the `group=` argument, which only supplies the cluster variable for p-values generated from mixed effects models, yeah? Could it just be an argument only to `add_p()` instead, since that is the only function where it is used?

I think the shorter names you mention are not descriptive enough. What about `tableR`?

CRAN is on downtime until like August 18th so you'll have to wait until they're back to submit.

**Comment by margarethannum** [comment]
1. I absolutely agree that `group =` argument name should be changed. Although now that I'm looking at the documentation for this argument I think it is a little vague, does it actually have anything to do with grouping variables? How did you imagine it would be used? Is it just a stopgap if someone doesn't want to do select() to their data beforehand? (e.g. trial %>% tbl_summary(group = "age")

2. I still like the name {gtsummary} :)

**Comment by margarethannum** [comment]
I second @zabore's  suggestion that `group` argument just be included in `add_p()` since that is where it is applicable!

**Comment by karissawhiting** [comment]
I like the name! Also, since gt has plans to support word outputs, it sounds like it will be possible to go full gt dependence in the future. 

I've never used the group argument, but based on the name I assumed it had to do with grouped data frames (which it sounds like it doesn't) so I also support the above suggestions about adding it to `add_p()` only where it is applicable, and updating the argument name/doc descriptions to reflect.

**Comment by ddsjoberg** [comment]
OK!  the `group` argument is now only in `add_p`.

I think we're good to go to OpenSci! YAY!
