### ISSUE TITLE
giving vector of digits to tbl_summary does not round correctly

### ISSUE THREAD

**Issue by emilyvertosick** [ddsjoberg/gtsummary#285]
When giving a vector of multiple numbers to the "digits" argument, all numbers are rounded to the same number of digits.

``` r
library(tidyverse)
library(gtsummary)

trial %>%
  select(marker, trt) %>%
  tbl_summary(
    by = trt,
    # change statistics printed in table
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list("marker" ~ c(1, 2))
  )
```
![image](https://user-images.githubusercontent.com/49212917/68246998-ee2d8680-ffe7-11e9-9142-3ab9805df1d0.png)

<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ddsjoberg** [comment]
@emilyvertosick thank you for reporting!

@margarethannum this is exactly what we were just discussing re: unit tests.  A recent update broke this functionality, but did not cause any error.  If we had a unit test checking that the proper formatting was actually performed (rather than unit tests that just check for no errors), the update would not have made it into the master branch.  Oy so hard!
