### ISSUE TITLE
Number Missing in Cell

### ISSUE THREAD

**Issue by MyKo101** [ddsjoberg/gtsummary#402]
I'd like to present number of missing in the same cell as the rest of my statistics, rather than on a separate row in my table. However, I understand that the way in which user-defined functions are used, by default it omits all missing values *before* evaluating. Because of this, the following doesn't work:

```r
nmiss <- function(x) sum(is.na(x))
nonmiss <- function(x) sum(!is.na(x))
tbl <- tibble(x = c(1:20,NA,NA))
nmiss(tbl$x)
tbl %>%
  tbl_summary(missing="no",
              statistic = list(all_continuous() ~ "({nonmiss} : {nmiss})"))
```
Is there a workaround? Or a possible future feature?

I know I could use `add_n()` to add the number of missing in as a new column, but this doesn't currently support the `by = ` argument.

**Comment by ddsjoberg** [comment]
Hi @MyKo101 , thanks for the question!

I have never thought of doing this before, and when I read your code I thought it would work!  The reason it did not work out, however, is because missing values are filtered out before calculating summary statistics.  Rather than seeing (20 : 2) like you wanted, you were seeing (20 : 0) because the 2 missing values were omitted from the calculation.

There is a relatively easy workaround.  Before passing the data frame to `tbl_summary()`, make each variable a TRUE/FALSE depending on its missing status.  Then summarize as a dichotomous variable.

```r
library(gtsummary)
library(tidyverse)

tbl <- 
  tibble(x = c(1:20,NA,NA)) %>%
  mutate_all(~!is.na(.)) # converting to T/F if missing

tbl %>%
  tbl_summary(
    missing = "no",
    statistic = list(everything() ~ "({n} : {N - n})")
  )
```

**Comment by MyKo101** [comment]
Hi @ddsjoberg. Thanks for the reply.

I understand the reasoning behind it. Makes perfect sense to omit the NAs for the summary statistic as it would make the evaluation of user-defined functions easier.

The workaround works fine for that example, but it's just a simplified example. This wouldn't work if, for example, I wanted the mean and the number missing (which is actually closer to my use-case)

```r
nmiss <- function(x) sum(is.na(x))
tbl <- tibble(x = c(1:20,NA,NA))
nmiss(tbl$x)
tbl %>%
  tbl_summary(missing="no",
              statistic = list(all_continuous() ~ "{mean} ({nmiss})"))
```

**Comment by ddsjoberg** [comment]
@MyKo101 you're exactly right...we did it this way so user-defined functions wouldn't need to include arguments like `na.rm=TRUE`.

I'll think on this more...perhaps we could include standard statistics for each variable, like `N`, `n`, and `nmiss`.   Or something else that allows for printing the Ns!

Thanks again for the question!
