### ISSUE TITLE
Suggestion: Update trial data set with stronger relationships

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#408]
There are not many significant p-values reported in our examples (tbl_summary and tbl_regression).  Should we update trial to have stronger relationship built-in?

**Comment by higgi13425** [comment]
Would it be helpful to have access to more trial data from the `medicaldata` package?

https://github.com/higgi13425/medicaldata

**Comment by ddsjoberg** [comment]
@higgi13425 i didn't know about these!  i'll check them out!

**Comment by ddsjoberg** [comment]
closing without updating....it would break a lot of unit tests and would be annoying :|

**Comment by higgi13425** [comment]
OK.I could write a vignette with medical data if that would be helpful?
    On Sunday, January 3, 2021, 03:20:51 PM EST, Daniel Sjoberg <notifications@github.com> wrote:  
 
 


closing without updating....it would break a lot of unit tests and would be annoying :|

**Comment by ddsjoberg** [comment]
@higgi13425 hey hey!

What did you have in mind? What I was originally thinking with this issue was to update the trial data set in gtsummary. It's the data used in every help file example and the vignettes. Lots of the pvalues are large and I thought the results would look more interesting with significant results.

Ultimately, I would be a big project to change the trial dataset at this point, because there are so many unit tests that check accuracy of results against the data. 

We're you thinking a new vignette? Adding to existing? I need to check out your learner tutorial again! I haven't looked at it since you mentioned it.

**Comment by higgi13425** [comment]
Hi Daniel,
I was thinking about a new Rmd vignette, if that would be helpful, using one of the {medicaldata} datasets.
I am still putting the pieces in place, but the test chapter on filtering (chapter 4 here RStudio Connect) is

| 
| 
|  | 
RStudio Connect


 |

 |

 |

 coming along.
Peter

    On Monday, January 4, 2021, 10:10:56 PM EST, Daniel Sjoberg <notifications@github.com> wrote:  
 
 


@higgi13425 hey hey!

What did you have in mind? What I was originally thinking with this issue was to update the trial data set in gtsummary. It's the data used in every help file example and the vignettes. Lots of the pvalues are large and I thought the results would look more interesting with significant results.

Ultimately, I would be a big project to change the trial dataset at this point, because there are so many unit tests that check accuracy of results against the data.

We're you thinking a new vignette? Adding to existing? I need to check out your learner tutorial again! I haven't looked at it since you mentioned it.
