### ISSUE TITLE
Suggestion: Create an add-in or local Shiny app to help users construct summary tables

### ISSUE THREAD

**Issue by ddsjoberg** [ddsjoberg/gtsummary#409]
I am not sure how feasible this is....can we create an add-in or Shiny app that is run in a users local R session that can interactively help users construct summary tables.
https://rstudio.github.io/rstudioaddins/#shiny-gadgets

**Comment by ddsjoberg** [comment]
Good example here: https://github.com/MayaGans/tidyCDISC (repo temporarily removed...hopefully coming back soon)

**Comment by larmarange** [comment]
It would be so great and helpful for beginners. I'm thinking in particular to students in first or second year.

For an example of interface, you could have a look to esquisse package who propose an interface for ggplot2 graphs

**Comment by ddsjoberg** [comment]
@ironwest has already started on one

https://twitter.com/NorimitsuNishi1/status/1328694692158967809?s=19

**Comment by larmarange** [comment]
Thanks a lot for the information.

@ironwest I have played with it and it's already quite **impressive**!

@ddsjoberg would such type of work be one day integrate `gtsummary` as an officiel add-in or will be something independant?

If I may provide some comments:

- I have the feeling that `egsummary` was first developed as a Shiny app rather than an addin: data should be imported as a CSV file and the app offers button to reexport results. On the other hand, an add-in should be much more focused on generating code as an helper for users --> instead of importing a CSV file we should be able to select a data.frame availble in the environment.
- For an addin, it would be better to stay directly in RStudio instead of opening the app in a webbrowser. A button to copy the produced code should be avialble and (even better) the code could be integrated directly in a script (addins provided by `questionr` for factor recoding are a good example of that spirit)
- The options should be by default the default values of `tbl_summary()`
- One important thing (in particular for learning `gtsummary`) is the quality of the produced code. Some option should be added in the code **only** if they differ from the default value. For example, `type` argument should not be part of the generated code except if users change the type of a specific variable.
- In the select variables box, if a data frame is imported, it would be nice to display variable labels as well
- When a group by variable is selected, it would be nice to be able to select the type of percentage
- The digits argument could be splitted for continuous and for categorical variables, and should offer as much values as there is statitics displayed (e.g. if 3 statistics are displayed for continuous variables, we should have the opportunity to select 3 different values)
- An option to have the opportunity to include or not missing values is missing (`missing` argument of `tbl_summary()`)
- For variable label settings and variable type settings, it could be difficult to read when there is a lot of variables. Maybe relevant to limit that view only to variables that have been selected.
- Just for information, the variable label setting does not seem to work on my PC
- For variable label settings, could be nice to have the option to custom the way they are displayed, as it is offered for the Overall label.
- Would be also great to have the opportunity to select a specific theme, at least `theme_gtsummary_language` which have most of the basic needs

Once again, it is a great beta interface. And I completely understand the needs of an autonomous Shiny app are quite different from the needs of a proper add-in.

Regards

**Comment by ironwest** [comment]
Hi @larmarange.

Thank you for the comment and my apology for the slow response.
After using gtsummary for my projects, I now feel "I" need addin for research projects.

As you mentioned to @ddsjoberg, I will try to work on add-in as you described in the post.

@ddsjoberg:
 I'm not sure if the add-in should be included in the original package, but I will challenge to make an add-in package first.

Regards

**Comment by ddsjoberg** [comment]
hey @ironwest ! sounds great!  I like your suggestion to create it as an addin package first.

**Comment by ironwest** [comment]
@ddsjoberg, @larmarange 
I initiated work on "gtsummary_addin."
The package name is temporary and may change to a better name if there is any suggestion. 
 Though, the current version is very buggy. I will work to improve it.

Package placed in here:
https://github.com/ironwest/gtsummary_addin

**Comment by larmarange** [comment]
@ironwest That's great!!!

Let us know if you need / want some testing and when.

All the best

**Comment by larmarange** [comment]
Thanks a lot @ironwest   and sorry for my late feedback, but I'm currently overloaded with my regular work.

First of all, it's very great!!!!  Please find below some feedbacks regarding tbl_summary addin:

- when loading, by default all variables are selected. If the data.frame has a lot of variables, it could be a problem because the initial table will be very long to display. Maybe, it could be wise to test the number of columns in the data.frame and to unselect all variables if this number is high
- I didn't find any button to change the selected data.frame. If I selected the wrong data frame, I have to close the addin and to restart it
- Currently, the addin is loaded in the web browser. But there is no button to close it and I have to manually select stop in RStudio. It's not the most intuitive. A more intuitive option could be to do like `questionr` packages. The addin is open in a RStudio window. You have a close button. And when you close it, the code is directly pasted in the script.
- in the variables selector, it would be nice to also display the variable label (if exitsts, eventuellement with a `str_trunc()` in case labels are too long) as it would help to identify the variables to display
- overall the interface is really great. Maybe, it could be relevant near- ertain item to add a clickable help icon with links to gtsummary documentation website
- there is an issue with **Variable Label Setting**: it seems not possible to custom only certain variables or to remove customization. Often, most variable labels are correct and just one or two needs customization. It would be better if by default the field were empty, and to consider that an empty field means *no label customization*.

Anyway, This is absolutely GREAT !!!!!!!!

Would be great to see (once the adding for tbl_summary finalized) the same addin for tbl_svysummary

**Comment by ironwest** [comment]
Hi @larmarange. Thanks for the feedback. I think most of your feedbacks will improve the user experience if implemented properly. So, I will tackle those after finishing the remaining tbl_merge add-in and customization add-in. 

I have a question about your last feedback:

> here is an issue with Variable Label Setting: it seems not possible to custom only certain variables or to remove customization. Often, most variable labels are correct, and just one or two needs customization. It would be better if, by default the field were empty and to consider that an empty field means no label customization.

Since I usually do not use labels for variables in data.frame, I probably do not fully understand what you meant here. If you provide me an example data with the label, I can work out the meaning of feedback. Is there any good built-in dataset for this purpose?

**Comment by ironwest** [comment]
@larmarange 
And, I feel like it is better to post about these issues in

https://github.com/ironwest/gtsummary_addin/issues

(I made issues based on your feedback there. )

**Comment by ddsjoberg** [comment]
I love this idea, but the building and maintenance time of a shiny app is something I can't commit to. Unfortunately, closing this issue
