### ISSUE TITLE
tbl_summary issue

### ISSUE THREAD

**Issue by dax44** [ddsjoberg/gtsummary#466]
I have some data with five variables, all numeric. When I type str(data) I see this

> data.frame:	62 obs. of  5 variables:
 $ v_1t : num  0 0.1 0.1 0.1 0 0.1 0.5 0.3 0.1 0 ...
 $ v_1m : num  0 0.1 0.22 0.1 0 0.1 0.8 0.22 0.1 0 ...
 $ v_3m : num  0 0.1 0 0.1 0 0.1 0.3 0.1 0.1 0 ...
 $ v_6m : num  0 0.1 0 0.1 0 0.1 0.22 0.22 0.1 0 ...
 $ v_12m: num  0 0.1 0 0.1 0 0.3 0.22 0.22 0 0 ...

but data %>% tbl_summary() gave me something strange

![Rplot](https://user-images.githubusercontent.com/8738353/80151512-79accb00-85ba-11ea-8450-1386b6648c55.png)

Have you any idea what's wrong?

**Comment by ddsjoberg** [comment]
The function guesses if a variable is continuous or categorical. Since there a few unique values for the one variable, it guessed categorical.  Use the `type=` argument to override the default and make it continuous.  If all your columns are continuous you can use `type = everything() ~ "continuous"`.

I hope that helps!!

Happy to help if you have other questions about the package! Please use stackoverflow.com to post your questions, and use the [gtsummary] tag so me or another author will be alerted to the question.

Thanks!

**Comment by dax44** [comment]
Thank you for quick help. Indeed everything() ~ "continuous" fix the problem.
Best regards

**Comment by ddsjoberg** [comment]
Great!  Happy coding!!
