### ISSUE TITLE
Strange output of tbl_cross

### ISSUE THREAD

**Issue by dax44** [ddsjoberg/gtsummary#506]
Strange things happened when rows has "No" values.
`tab <- data.frame(
    X = rep(c("Yes", "No"), 3),
    Y = rep(c("Yes", "No"), each = 3)
)` 

simple table gives me 

`table(tab$X, tab$Y)`

```
      No Yes
  No   2   1
  Yes  1   2
```

but 

`tab %>% 
    tbl_cross(row = X,
              col = Y)`
gives

![image](https://user-images.githubusercontent.com/8738353/83053092-7ccf2700-a050-11ea-9a56-b3a6ad0a63e2.png)

Please help!

**Comment by dax44** [comment]
Update...
when I added

`tab %>% 
    tbl_cross(row = X,
              col = Y,
              missing = "always")`

![image](https://user-images.githubusercontent.com/8738353/83053410-f404bb00-a050-11ea-98e8-4cc1fffcead6.png)

**Comment by karissawhiting** [comment]
`tbl_cross()` is a wrapper for `tbl_summary()` which assumes variables coded as TRUE/FALSE, 0/1, or yes/no are dichotomous and therefore only the TRUE, 1 and yes rows are displayed. 

Since this is awkward with cross tables, we can change the default in the `tbl_summary()` call within `tbl_cross()` to have `type = everything() ~ "categorical"`.

**Comment by dax44** [comment]
Thank you for your help. It works :)

**Comment by ddsjoberg** [comment]
@dax44 thanks for the report! The bug is fixed in the dev version and you can install it with `remotes::install_github("ddsjoberg/gtsummary")`

Thanks for updating so quickly @karissawhiting !!!
