### ISSUE TITLE
Expressions in the statistic argument of tbl_summary

### ISSUE THREAD

**Issue by UAB-BST-680** [ddsjoberg/gtsummary#561]
First, thank you for all of your hard work and dedication to the `gtsummary` package. It is really amazing. 

I'd like to request a feature in `tbl_summary()` that would allow more flexible expressions to be used in the `statistic` argument. (see reprex below). Would it be possible to write expressions inside of the character string that is evaluated on the right hand side of these formulas?

``` r
library(gtsummary)

# This works great!
trial %>% 
  tbl_summary(by = trt, 
    statistic = all_continuous() ~ "{median} ({p25}, {p75})")
```

``` r

# Can we make this work? (i.e., can we make it so that expressions such as mean +/- sd are evaluated correctly?) 
trial %>% 
  tbl_summary(by = trt, 
    statistic = all_continuous() ~ "{mean} ({mean - sd}, {mean + sd})")
#> Warning: Values are not uniquely identified; output will contain list-cols.
#> * Use `values_fn = list` to suppress this warning.
#> * Use `values_fn = length` to identify where the duplicates arise
#> * Use `values_fn = {summary_fun}` to summarise duplicates
#> Warning: Outer names are only allowed for unnamed scalar atomic inputs
#> Error: Problem with `mutate()` input `df_stats`.
#> x Can't recycle `by` (size 2) to match `..3` (size 3).
#> i Input `df_stats` is `pmap(...)`.
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Is your feature request related to a problem? Please describe.**
Not related to a specific problem, just something that has come up in conversations with my students (@jinhong-cui @Li-Zhang28).

**Comment by ddsjoberg** [comment]
Hi @UAB-BST-680 ! I am so happy to hear you and your students have found the package helpful :)

That syntax would certainly make some things easier, but it would cause an issue.  The issue arises because in the syntax `"{mean} ({sd})"`, mean and sd are doing double duty: defining the function to use to summarize data, AND using the standard glue syntax to place the statistic. If it were not for the double usage, it would be relatively easy to implement something like this. 

If we were to implement this, this is what we'd need to do:
1. Take the string input, e.g. `"{mean} ({mean - sd}, {mean + sd})"`, and extract everything between the curly brackets, leaving us this vector `c("mean", "mean - sd", "mean + sd")`. This is easy enough to do, and it already done within the package.
1. The next step would be more difficult.  Ideally, we'd convert the vector above into a vector of three functions...the last two we would need to create ourselves somehow.  We'd need three distinct functions to preserve all the syntax related rounding and formatting results (how we would specify the formatting for each of the presented statistics). It's this step that I don't have confidence that I could implement robustly.  Sure, our example wouldn't be so bad, but generalizing would be quite difficult I think.

I would give these advice to your students, if they wish to present these statistics often when using gtsummary.
1. Create a personal R package (I think everyone should have one!), and add functions like `mean_plus_sd()` and `mean_minus_sd()`. Then you'll easily be able to create the tables you need without needing to define the functions each time.
1. If you want to go even further, they can make these set of statistics the default statistics presented using gtsummary themes (http://www.danieldsjoberg.com/gtsummary/articles/themes.html using the `tbl_summary-arg:statistic` theme element).

Happy Coding, and please don't hesitate to be in contact with feature requests! 🕺

**Comment by ddsjoberg** [comment]
Hmmm, thinking on this more.... Perhaps the syntax could be something like this:

`"{mean} {~mean(.) + sd(.)}"`

I'll leave this issue open and think on it more....

**Comment by ddsjoberg** [comment]
Hi @UAB-BST-680 !

I have been thinking about the implications of introducing something like this, and I think in the end it will cause more confusion than it does help.  The primary reason for this is the downstream changes it would lead to.

I did take the time to read up more on the shortcut notation using `~` and will not accept it for other functions' arguments.

Please do feel free to reach out with feature requests in the future!

> - [ ] Allow for the shortcut notation when specifying statistics to present in `tbl_summary(statistic = all_continuous() ~ "~mean(.)")`
    - Typically, the function name does double-duty specifying the placement of the statistic AND naming the R function.
    - Allowing the shortcut notation means we will need to separate these duties internally.  My first inclination is to parse out a separate vector of functions to apply, and a second vector of function names.  The shortcut notation will not have names---I think I will name them `..1`, `..2`, etc. depending where they fall in the order of statistics presented.
    - This will have implications for the footnote: we won't know what to call the statistic. Should we just print a note that we don't have a label and the footnote has not been placed? We could also print instructions on how to create a footnote with `modify_footnote()`.
    - There will also be implications for how `inline_text()` refers to the statistics when `pattern=` arg is used.
    - This portion of the update should wait for `tbl_svysummary()` to be merged, as much of the code overlaps with `tbl_summary()`.
