### ISSUE TITLE
Error with diamonds dataset (ordered factors?)

### ISSUE THREAD

**Issue by gorkang** [ddsjoberg/gtsummary#567]
When using gtsummary() in the diamonds dataset, there is an error. 

Please see a reprex below:

``` r
library(dplyr)
library(ggplot2)
library(gtsummary)

  gtsummary::tbl_summary(diamonds, by = cut) %>%
    gtsummary::add_n()
#> Error: Problem with `mutate()` input `df_stats`.
#> x Can't join on `x$variable` x `y$variable` because of incompatible types.
#> ℹ `x$variable` is of type <ordered<bd2ad>>>.
#> ℹ `y$variable` is of type <factor<bd2ad>>>.
#> ℹ Input `df_stats` is `pmap(...)`.
```

**Comment by ddsjoberg** [comment]
Thank you @gorkang for reporting!  I never use ordered factors and didn't add a check for this previously!

The bug is fixed, and will be reviewed in https://github.com/ddsjoberg/gtsummary/pull/568

In the meantime, while the update is reviewed and merged, you can use the code below to strip the ordered class from the factor before passing to `tbl_summary()`.

```r
ggplot2::diamonds %>%
  # remove ordered class from factor variables
  dplyr::mutate_if(~inherits(., "ordered"), ~factor(., ordered = FALSE)) %>%
  gtsummary::tbl_summary(by = cut) %>%
  gtsummary::add_n()
```
![image](https://user-images.githubusercontent.com/26774684/86922468-afae1580-c0fa-11ea-90ce-6c888ca46bb7.png)
