### ISSUE TITLE
New line for statistic list output.

### ISSUE THREAD

**Issue by juseer** [ddsjoberg/gtsummary#592]
**Is your feature request related to a problem? Please describe.**
While output multiple statistic values, e.g. min ~ max, mean ± sd, a new line to separate those values could be very helpful. Yet, glue syntax seems not working.
```
statistic = list(all_continuous() ~ 
                                 "{min} ~ {max} \n {mean} ± {sd}"))
```

**Describe the solution you'd like**
output:
```
min ~ max
mean ± SD
```

**Comment by ddsjoberg** [comment]
Hi @juseer !

By default, gtsummary tables are printed with the {gt} package, and I don't believe there is a way for a line break within a cell using gt. (I hope they add this in the future!)

BUT, you can print the table with flextable, which does allow for the linebreaks.
1. You'll need to install the dev version of gtsummary (will be released in a couple of weeks) 
    - `remotes::install_github("ddsjoberg/gtsummary")`

1. Then use the `as_flex_table()` function to convert the gtsummary object to a flextable.

Here's an example. You may want to pipe an additional flextable function to justify the label to the top of the cell (rather than centered). I also updated the footnote because the line break also appeared there and it looked funny.
```r
library(gtsummary)

trial %>%
  select(age, marker) %>%
  tbl_summary(
    statistic = list(all_continuous() ~ "{min} ~ {max} \n {mean} ± {sd}")
  ) %>%
  modify_footnote(starts_with("stat_") ~ "Range and mean±SD") %>%
  as_flex_table() %>%
  flextable::foo() # a function that updates the justification of flextables
```

![image](https://user-images.githubusercontent.com/26774684/88847352-eb497600-d1b4-11ea-897a-b19ab61bcbd7.png)

**Comment by ddsjoberg** [comment]
Hello @juseer ! Let me know if this solution works for you. If you have further questions about this topic, please feel free to reopen the issue. 🕺

**Comment by juseer** [comment]
> Hi @juseer !
> 
> By default, gtsummary tables are printed with the {gt} package, and I don't believe there is a way for a line break within a cell using gt. (I hope they add this in the future!)
> 
> BUT, you can print the table with flextable, which does allow for the linebreaks.
> 
> 1. You'll need to install the dev version of gtsummary (will be released in a couple of weeks)
>    
>    * `remotes::install_github("ddsjoberg/gtsummary")`
> 2. Then use the `as_flex_table()` function to convert the gtsummary object to a flextable.
> 
> Here's an example. You may want to pipe an additional flextable function to justify the label to the top of the cell (rather than centered). I also updated the footnote because the line break also appeared there and it looked funny.
> 
> ```r
> library(gtsummary)
> 
> trial %>%
>   select(age, marker) %>%
>   tbl_summary(
>     statistic = list(all_continuous() ~ "{min} ~ {max} \n {mean} ± {sd}")
>   ) %>%
>   modify_footnote(starts_with("stat_") ~ "Range and mean±SD") %>%
>   as_flex_table() %>%
>   flextable::foo() # a function that updates the justification of flextables
> ```
> 
> ![image](https://user-images.githubusercontent.com/26774684/88847352-eb497600-d1b4-11ea-897a-b19ab61bcbd7.png)

Look forward the new release. This is a good solution, but my working environment seems to complain about the package installation, which might be irrelevant.

**Comment by ddsjoberg** [comment]
If you're having difficulties installing, I would.
1. Close ALL R/RStudio sessions.
1. Open a single session and update your tidyverse packages with `tidyverse::tidyverse_update()`
1. Install flextable. If you're on a mac and have troubles, there may be a secondary program you need to install called X11 or XQuartz. 
1. Then re-start, and install dev version of gtsummary.
