### ISSUE TITLE
Standard errors or confidence intervals below estimates

### ISSUE THREAD

**Issue by djbirke** [ddsjoberg/gtsummary#675]
Regression results are often reported in tables in which each column represents a different regression model and the rows display the estimates of the independent variables that are used in (a subset) of those models.

In these tables, standard errors (or confidence intervals) are typically shown below each estimate to preserve the structure of "one column" = "one regression model".    

How can I create such a table from a list of `lm` objects using `gt` and `gtsummary`?

This is a common request, for examples see StackOverflow posts [1](https://stackoverflow.com/questions/5359286/output-a-table-with-standard-errors-below-estimates), [2](https://stackoverflow.com/questions/63851965/how-to-move-standard-error-below-or-next-to-an-estimate-in-a-table-in-r) and [3](https://stackoverflow.com/questions/63649937/how-to-put-standard-error-below-estimate-in-a-table-in-r-and-transfer-to-flexta).

Here is an example:
<img width="1146" alt="table" src="https://user-images.githubusercontent.com/21116842/95286256-b17d9700-0817-11eb-9324-9ed05d7bb885.png">

**Comment by ddsjoberg** [comment]
Hi @djbirke ! Thank you for the note!  

There are many fields that present models this way, and many R packages that help get the models into this format....unfortunately, gtsummary is not one of them!  One of the primary reasons we wrote the package is because the other R packages presented models the way you're requesting, and this is not how models are shown in the medical research literature.

As there are other packages available for this, supporting this output type is not on our list of features to implement. Apologies!

**Comment by djbirke** [comment]
Okay, thank you for being clear about it.

**Comment by ddsjoberg** [comment]
hello again @djbirke !

I wanted to let you know that your request has been echoed may times since your original post here. In the next version of gtsummary (will be released in a few days), there is support for these types of model outputs via the `add_significance_stars()` function.

Check out the third example in the help file.
http://www.danieldsjoberg.com/gtsummary/dev/reference/add_significance_stars.html
![image](https://user-images.githubusercontent.com/26774684/114396303-6b5d1380-9b6b-11eb-8805-62711dd48b78.png)

When the gt package supports line breaks for all output types, I'll make the integration more seamless likely via a journal theme.
https://github.com/rstudio/gt/issues/547

**Comment by djbirke** [comment]
@ddsjoberg That's great news; I expect this feature to help grow gtsummary's user base. Thank you for your work on this!
