### ISSUE TITLE
style_percent() function does not work with digits argument

### ISSUE THREAD

**Issue by Pascal-Schmidt** [ddsjoberg/gtsummary#690]
The `style_percent` function does not work when using the digits argument from the `base::format()` function. I believe this is because the `style_percent` function uses the digits argument from the `style_number` function. Is there a workaround for this?

```r
percent_vals <- c(-1, 0, 0.0001, 0.005, 0.01, 0.10, 0.45356, 0.99, 1.45)
gtsummary::style_percent(percent_vals, digits = 2)
```

**Comment by larmarange** [comment]
There is an automatic rule to determine the number of digits. 

Dear @ddsjoberg  maybe you could opt for an argument `digits = NULL` by default.

If NULL, you maintain the current behaviour. If specified, you apply the value provided.

**Comment by ddsjoberg** [comment]
Thank you for the report!  All other `style_*()` functions in gtsummary have a digits argument that control the number of digits reported, and `style_percent()` should have one too.  I'll update to include one.  

A side note:
The `style_*()` functions we're written for internal use within gtsummary, and I would say are more incidentally exported rather than written to be more incredibly general.  The benefit to working within the `style_*()` family, however, is that some formatting options are controlled by the gtsummary themes (@Pascal-Schmidt I saw that you're using this in the theme you posted on stackoverflow). Anyway, `style_number()` is the little workhorse behind all these functions, and `style_number()` is basically a low-rent version of `scales::number()`.  If you write a small function that formats percentages just how you like _and_ you use `style_number()` to do the rounding, then your function's formatting options will also be controlled by the applicable gtsummary theme options.
