### ISSUE TITLE
gtsummary has been archived on CRAN

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#798]
Please check https://cran.r-project.org/web/packages/gtsummary/index.html

gtsummary has been removed from CRAN the 26 Feb 2021

**Comment by ddsjoberg** [comment]
FYI I had received a message from cran 2 weeks ago about huxtable being archived, and we'll be archived if we don't fix gtsummary's failing checks. Huxtable shortly was returned to CRAN and all the gtsummary checks once again passed. I responded to their email, explained huxtable was back and our checks were now passing. I didn't get a response, bit didn't think too much of it since all the CRAN checks were fine.

Anyway, they archived us this morning, but we're back up again after a resubmission that was identical to the previous version.

**Comment by larmarange** [comment]
Thanks.  I received this morning an email from CRAN that broom.helpers did not pass checks, and it was due to the removal of gtsummary.
