### ISSUE TITLE
Use emmeans::joint_tests as alternative for add_global_p

### ISSUE THREAD

**Issue by StaffanBetner** [ddsjoberg/gtsummary#801]
For e.g. geeglm models car::Anova isn't supported, but emmeans::joint_tests work fine (which is a Type III-test). It would be good if there could be an option to use that instead of car::Anova in add_global_p to support more models.

**Comment by ddsjoberg** [comment]
Hey @StaffanBetner ! Thank you for the note.  I like the idea. I am only hesitant because it adds another package dependency, and I have come to learn that dependency management is the _worst_.

Here's an example how you can use `joint_tests()` and get the results in the gtsummary table.

``` r
library(gtsummary)
packageVersion("gtsummary")
#> [1] '1.3.7'

mod <- lm(marker ~ age + grade, trial)
tbl <- tbl_regression(mod)

df_test <-
  emmeans::joint_tests(mod) %>%
  tibble::as_tibble() %>%
  select(variable = `model term`, last_col()) %>%
  mutate(row_type = "label",
         label = c("Age", "Grade"))

# merge `joint_tests` with gtsummary table
tbl %>%
  modify_table_body(
    dplyr::rows_update,
    df_test,
    by = c("variable", "label", "row_type")
  ) %>%
  as_kable() # convert to kable to display on github
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Characteristic</strong></th>
<th style="text-align: left;"><strong>Beta</strong></th>
<th style="text-align: left;"><strong>95% CI</strong></th>
<th style="text-align: left;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Age</td>
<td style="text-align: left;">0.00</td>
<td style="text-align: left;">-0.01, 0.01</td>
<td style="text-align: left;">&gt;0.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grade</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.047</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">II</td>
<td style="text-align: left;">-0.38</td>
<td style="text-align: left;">-0.69, -0.07</td>
<td style="text-align: left;">0.015</td>
</tr>
<tr class="odd">
<td style="text-align: left;">III</td>
<td style="text-align: left;">-0.12</td>
<td style="text-align: left;">-0.43, 0.19</td>
<td style="text-align: left;">0.5</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-02-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by StaffanBetner** [comment]
Ah, splendid! Thank you for that suggestion! Easy to write a function for that. :)

**Comment by ddsjoberg** [comment]
Great! If you'd like any assistance constructing a function, happy to take a look.
