### ISSUE TITLE
tbl_regression no longer working for rstanarm models

### ISSUE THREAD

**Issue by iaingallagher** [ddsjoberg/gtsummary#816]
```tbl_regression``` throws an error when using models made with ```rstanarm```.

```r
library(rstanarm)
library(gtsummary)
z <- stan_glm(response ~ age + grade, data = trial, refresh = 0, family = binomial)
tbl_regression(z, exponentiate = TRUE)
```
Results in:

```r
Registered S3 method overwritten by 'broom.mixed':
  method      from 
  tidy.gamlss broom
Error in colSums(tcm * w) : 
  'x' must be an array of at least two dimensions
```

**Comment by larmarange** [comment]
OK, it seems that now `weights(z)` return a zero-length vector instead of `NULL`, resulting in an error when computing `n` columns.

This simple change https://github.com/larmarange/broom.helpers/commit/bbb45a64be1681a00769bb51b85e15682a7f8c82  should fixed the problem

**Comment by ddsjoberg** [comment]
maybe for `add_n()` we could wrap it in a `tryCatch()` for `tidy_plus_plus()` in case of other subsequent unanticipated changes?

**Comment by larmarange** [comment]
in fact, it appears that `rstanarm::stan_glm()` have never been tested before by `broom.helpers` (we added only support of `brmsfit()`). Now there is a test.

With a `tryCatch()`, the bug would have not been visible and therefore it would have not been possible to fix it.

**Comment by ddsjoberg** [comment]
Thanks @larmarange for you quick fixes and dedication!

For this model type, it seems the model term isn't parsed from the variable level, and it shows `"gradeII"` instead of `"II"` in the label column and reference row is not added.  Is that because there is no terms function for rstanarm models? I thought in those cases we printed a note?

devtools::install_github("larmarange/broom.helpers")
devtools::install_github("ddsjoberg/gtsummary")
packageVersion("broom.helpers")
packageVersion("gtsummary")
library(magrittr)

z <- 
  rstanarm::stan_glm(response ~ age + grade, 
                     data = gtsummary::trial, 
                     refresh = 0, 
                     family = binomial)

broom.helpers::tidy_plus_plus(z,
                              tidy_fun = broom.mixed::tidy,
                              add_reference_rows = TRUE) %>% 
  dplyr::select(term, variable, var_label, var_type, label, estimate) %>%
  knitr::kable()

gtsummary::tbl_regression(z, exponentiate = TRUE) %>% gtsummary::as_kable()

**Comment by larmarange** [comment]
OK

after exploration, it is due to the fact that the list of contrasts was not retrieved using the two main approaches used so far. But could be retrieved using a third approach.

`model_get_contrasts()` has been rewritten to try all three approaches. With this point fixed, all subsequent fucntions (including identication of reference rows) now works.   cf. https://github.com/larmarange/broom.helpers/commit/9bf0fe64f8d8bd2620a961c41990bc782787b8c2

**Comment by ddsjoberg** [comment]
wow, you're amazing @larmarange

**Comment by ddsjoberg** [comment]
thanks @iaingallagher for the report, and thank you @larmarange for the fixes!
