### ISSUE TITLE
Median CI by default for continuous variable in add_ci()

### ISSUE THREAD

**Issue by larmarange** [ddsjoberg/gtsummary#995]
By default, `tbl_summary()` displays the median for continuous variables. Therefore, it would be more consistent that `add_ci()` computes by default the confidence interval of the median for continuous variables.

It could be easily done with `wilcox.test(conf.int = TRUE)`.

Therefore I suggest:

- [ ] add a `wilcox.test` method to `add_ci()`
- [ ] by default, use `wilcox.test` for continuous variables
- [ ] if `theme_gtsummary_mean_sd()` is applied, change default to `t.test`

**Comment by ddsjoberg** [comment]
hey hey! @larmarange !

I like the idea of adding this. But I think I prefer to keep the default the mean difference, despite the default statistic in `tbl_summary()` being median IQR. Primarily, because the `wilcox.test()` gives a psuedo-median CI and I think most people wont' worry about when this actually is equivalent to the median.

**Comment by larmarange** [comment]
As you want.

Do we have a way to check if the displayed statistic is the median and not the mean, and to add a warnings/message to alert the user in such a case?

I'm just thinking about my students and the potential mistakes they could make.
